# https://cgit.drupalcode.org/drupal/tree/core/.eslintrc.json?h=8.5.x
---
extends: "./common.yml"
env:
  browser: true
  es6: true
  node: true
globals:
  Drupal: true
  drupalSettings: true
  drupalTranslations: true
  domready: true
  jQuery: true
  _: true
  matchMedia: true
  Backbone: true
  Modernizr: true
  CKEDITOR: true
